### ISSUE TITLE
TCP_FORWARDING = true results in failure of bastion_bootstrap.sh

### ISSUE THREAD

**Issue by Dombo** [aws-quickstart/quickstart-linux-bastion#11]
In the harden_ssh_security function you `touch /tmp/messages` which is only called when tcp_forwarding param is false. However your ubuntu_os // amazon_os functions assume the availability of this dir and chown it. This results in a critical failure.

I'm happy to PR if you could give me some contribution guidelines.

Thanks,
Dom

Begin dump of /var/log/cfn-init.log

```
2017-04-24 04:46:43,790 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.ap-southeast-2.amazonaws.com
2017-04-24 04:46:43,791 [DEBUG] Describing resource BastionLaunchConfiguration in stack Bastion
2017-04-24 04:46:44,256 [INFO] -----------------------Starting build-----------------------
2017-04-24 04:46:44,299 [DEBUG] Not setting a reboot trigger as scheduling support is not available
2017-04-24 04:46:44,300 [INFO] Running configSets: default
2017-04-24 04:46:44,301 [INFO] Running configSet default
2017-04-24 04:46:44,301 [INFO] Running config config
2017-04-24 04:46:44,301 [DEBUG] No packages specified
2017-04-24 04:46:44,301 [DEBUG] No groups specified
2017-04-24 04:46:44,301 [DEBUG] No users specified
2017-04-24 04:46:44,302 [DEBUG] No sources specified
2017-04-24 04:46:44,302 [DEBUG] Writing content to /tmp/bastion_bootstrap.sh
2017-04-24 04:46:44,302 [DEBUG] Retrieving contents from https://redacted.s3.amazonaws.com/linux/bastion/bastion_bootstrap.sh
2017-04-24 04:46:44,443 [DEBUG] Setting mode for /tmp/bastion_bootstrap.sh to 000550
2017-04-24 04:46:44,443 [DEBUG] Setting owner 0 and group 0 for /tmp/bastion_bootstrap.sh
2017-04-24 04:46:44,443 [DEBUG] Running command b-bootstrap
2017-04-24 04:46:44,443 [DEBUG] No test for command b-bootstrap
osrelease Ended
2017-04-24 04:46:44,713 [ERROR] Command b-bootstrap (./tmp/bastion_bootstrap.sh --banner https://redacted.s3.amazonaws.com/linux/bastion/banner_message.txt --enable true --tcp-forwarding true --x11-forwarding false) failed
2017-04-24 04:46:44,714 [DEBUG] Command b-bootstrap output: checkos Ended
BANNER_PATH = https://redacted.s3.amazonaws.com/linux/bastion/banner_message.txt
Creating Banner in /etc/ssh_banner
curl  -s https://redacted.s3.amazonaws.com/linux/bastion/banner_message.txt > /etc/ssh_banner
[INFO] Installing banner ... 
Setting up bastion session log in /var/log/bastion/bastion.log
Value of TCP_FORWARDING - true
Value of X11_FORWARDING - false
chown: cannot access '/tmp/messages': No such file or directory

2017-04-24 04:46:44,714 [ERROR] Error encountered during build of config: Command b-bootstrap failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 517, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 248, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command b-bootstrap failed
2017-04-24 04:46:44,714 [ERROR] -----------------------BUILD FAILED!------------------------
2017-04-24 04:46:44,718 [ERROR] Unhandled exception during build: Command b-bootstrap failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/EGG-INFO/scripts/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 118, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 505, in build
    self.run_config(config, worklog)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 517, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 248, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command b-bootstrap failed
2017-04-24 04:46:44,854 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.ap-southeast-2.amazonaws.com
2017-04-24 04:46:44,854 [DEBUG] Signaling resource BastionAutoScalingGroup in stack Bastion with unique ID i-00c594757dd394312 and status FAILURE

```

**Comment by avattathil** [comment]
Hello Dom,

Thanks for reporting this, please base your​ PR on the develop branch. Let
me know if you need help submitting the PR.

Thanks
--Tony

On Apr 23, 2017 10:02 PM, "Dom Hutton" <notifications@github.com> wrote:

In the harden_ssh_security function you touch /tmp/messages which is only
called when tcp_forwarding param is false. However your ubuntu_os //
amazon_os functions assume the availability of this dir and chown it. This
results in a critical failure.

I'm happy to PR if you could give me some contribution guidelines.

Thanks,
Dom

Begin dump of /var/log/cfn-init.log

2017-04-24 04:46:43,790 [DEBUG] CloudFormation client initialized with
endpoint https://cloudformation.ap-southeast-2.amazonaws.com
2017-04-24 04:46:43,791 [DEBUG] Describing resource
BastionLaunchConfiguration in stack Bastion
2017-04-24 04:46:44,256 [INFO] -----------------------Starting
build-----------------------
2017-04-24 04:46:44,299 [DEBUG] Not setting a reboot trigger as
scheduling support is not available
2017-04-24 04:46:44,300 [INFO] Running configSets: default
2017-04-24 04:46:44,301 [INFO] Running configSet default
2017-04-24 04:46:44,301 [INFO] Running config config
2017-04-24 04:46:44,301 [DEBUG] No packages specified
2017-04-24 04:46:44,301 [DEBUG] No groups specified
2017-04-24 04:46:44,301 [DEBUG] No users specified
2017-04-24 04:46:44,302 [DEBUG] No sources specified
2017-04-24 04:46:44,302 [DEBUG] Writing content to /tmp/bastion_bootstrap.sh
2017-04-24 04:46:44,302 [DEBUG] Retrieving contents from
https://redacted.s3.amazonaws.com/linux/bastion/bastion_bootstrap.sh
2017-04-24 <https://redacted.s3.amazonaws.com/linux/bastion/bastion_bootstrap.sh2017-04-24>
04:46:44,443 [DEBUG] Setting mode for /tmp/bastion_bootstrap.sh to
000550
2017-04-24 04:46:44,443 [DEBUG] Setting owner 0 and group 0 for
/tmp/bastion_bootstrap.sh
2017-04-24 04:46:44,443 [DEBUG] Running command b-bootstrap
2017-04-24 04:46:44,443 [DEBUG] No test for command b-bootstrap
osrelease Ended
2017-04-24 04:46:44,713 [ERROR] Command b-bootstrap
(./tmp/bastion_bootstrap.sh --banner
https://redacted.s3.amazonaws.com/linux/bastion/banner_message.txt
--enable true --tcp-forwarding true --x11-forwarding false) failed
2017-04-24 04:46:44,714 [DEBUG] Command b-bootstrap output: checkos Ended
BANNER_PATH = https://redacted.s3.amazonaws.com/linux/bastion/banner_message.txt
Creating Banner in /etc/ssh_banner
curl  -s https://redacted.s3.amazonaws.com/linux/bastion/banner_message.txt
> /etc/ssh_banner
[INFO] Installing banner ...
Setting up bastion session log in /var/log/bastion/bastion.log
Value of TCP_FORWARDING - true
Value of X11_FORWARDING - false
chown: cannot access '/tmp/messages': No such file or directory

2017-04-24 04:46:44,714 [ERROR] Error encountered during build of
config: Command b-bootstrap failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py",
line 517, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py",
line 248, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/command_tool.py",
line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command b-bootstrap failed
2017-04-24 04:46:44,714 [ERROR] -----------------------BUILD
FAILED!------------------------
2017-04-24 04:46:44,718 [ERROR] Unhandled exception during build:
Command b-bootstrap failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/EGG-INFO/scripts/cfn-init",
line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py",
line 118, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py",
line 505, in build
    self.run_config(config, worklog)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py",
line 517, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py",
line 248, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/command_tool.py",
line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command b-bootstrap failed
2017-04-24 04:46:44,854 [DEBUG] CloudFormation client initialized with
endpoint https://cloudformation.ap-southeast-2.amazonaws.com
2017-04-24 04:46:44,854 [DEBUG] Signaling resource
BastionAutoScalingGroup in stack Bastion with unique ID
i-00c594757dd394312 and status FAILURE


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/aws-quickstart/quickstart-linux-bastion/issues/11>, or mute
the thread

**Comment by Dombo** [comment]
Sorry if I'm mistaken but I believe I have based my branch on develop.

**Comment by Kostanos** [comment]
Hi, I have similar issue. Is this issue was resolved?
