### ISSUE TITLE
Bastion deployment fails due to issue with bootstrap script

### ISSUE THREAD

**Issue by andreykashcheev** [aws-quickstart/quickstart-linux-bastion#140]
**Summary**

Bastion deployment fails because EC2 instance fails to send "Done" signal to Cloud Formation. Looking at /var/log/cloud-init-output.log helped to identify the following error
```
+ sudo pip2 install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
  Downloading https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz (465 kB)
Collecting python-daemon<2.0,>=1.5.2
  Downloading python-daemon-1.6.1.tar.gz (47 kB)
Collecting pystache>=0.4.0
  Downloading pystache-0.6.0.tar.gz (78 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python2.7 /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpkcu0kU
       cwd: /tmp/pip-install-fo0k7e/pystache
  Complete output (17 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 183
      command = f"pandoc -f markdown-smart --write=rst --output={rst_temp_path} {md_path}"
                                                                                         ^
  SyntaxError: invalid syntax
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python2.7 /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpkcu0kU Check the logs for full command output.

```

My investigation indicates that this issue is caused by recent change in "pystache" package which removed support for Python 2.7:
https://pypi.org/project/pystache/0.6.0/

whereas according to build log, the 0.6.0 version gets installed:

```
Collecting pystache>=0.4.0
  Downloading pystache-0.6.0.tar.gz (78 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python2.7 /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpkcu0kU
       cwd: /tmp/pip-install-fo0k7e/pystache
```

Please fix this issue as soon as possible since it is causing deployment failure for Bastion template for all OS version which utilize Python2

**Priority** 

Blocker

**Comment by andreykashcheev** [comment]
The Bastion template works only with Amazon OS type since it uses Python3 but all other are failing deployment.

**Comment by troy-ameigh** [comment]
EKS fix is in EKS BootStrap. I am unable to duplicate this issue. It appears to be resolve for the bastion qs.
