### ISSUE TITLE
AutoScalingGroup : Received 1 FAILURE signal(s) out of 1

### ISSUE THREAD

**Issue by mseld** [aws-quickstart/quickstart-linux-bastion#93]
Received 1 FAILURE signal(s) out of 1. 
Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

<img width="1350" alt="Screenshot 2020-04-27 at 15 35 54" src="https://user-images.githubusercontent.com/9912550/80381526-5a0af080-88a1-11ea-9e27-4a94bf49fb67.png">

**Comment by mseld** [comment]
Machine logs

```
aws: error: argument --region: expected one argument

2020-04-27 13:30:42,324 [ERROR] Error encountered during build of config: Command b-bootstrap failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/site-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/site-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command b-bootstrap failed
2020-04-27 13:30:42,324 [ERROR] -----------------------BUILD FAILED!------------------------
2020-04-27 13:30:42,324 [ERROR] Unhandled exception during build: Command b-bootstrap failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/aws_cfn_bootstrap-1.4-py2.7.egg/EGG-INFO/scripts/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/local/lib/python2.7/site-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/local/lib/python2.7/site-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/local/lib/python2.7/site-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/site-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/site-packages/aws_cfn_bootstrap-1.4-py2.7.egg/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command b-bootstrap failed
2020-04-27 13:30:42,613 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.eu-west-1.amazonaws.com

2020-04-27 13:30:42,613 [DEBUG] Signaling resource BastionAutoScalingGroup in stack ESKibana-access with unique ID i-07e630c67b6d89097 and status FAILURE
```

**Comment by dmccue** [comment]
Adding: HealthCheckGracePeriod: '600' to the 'AWS::AutoScaling::AutoScalingGroup' properties resource should fix it

**Comment by Scott-Shackleton** [comment]
I have the same issue.

**Comment by Scott-Shackleton** [comment]
I had the same issue but was finally able to troubleshoot the issue by duplicating the quick-start files in my own S3 bucket and setting bastion_bootstrap.sh to public read.

**Comment by sivaprasad-kiranum** [comment]
I am getting the same error BastionAMIOS: Amazon-Linux-HVM while using the bastion host creation template for existing VPC in our stack.

Cloud init log
Jun 12 12:27:23 cloud-init[2841]: util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/part-001'] with allowed return codes [0] (shell=True, capture=False)
Jun 12 12:28:12 cloud-init[2841]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
Jun 12 12:28:12 cloud-init[2841]: util.py[DEBUG]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cloudinit/util.py", line 645, in runparts
    subp(prefix + [exe_path], capture=False, shell=True)
  File "/usr/lib/python2.7/dist-packages/cloudinit/util.py", line 1626, in subp
    # Just ensure blank instead of none?? (iff capturing)
ProcessExecutionError: Unexpected error while running command.
Command: ['/var/lib/cloud/instance/scripts/part-001']
Exit code: 1
Reason: -
Stdout: ''
Stderr: ''
Jun 12 12:28:12 cloud-init[2841]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Jun 12 12:28:12 cloud-init[2841]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Jun 12 12:28:12 cloud-init[2841]: util.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cloudinit/stages.py", line 660, in _run_modules
    cc.run(run_name, mod.handle, func_args, freq=freq)
  File "/usr/lib/python2.7/dist-packages/cloudinit/cloud.py", line 63, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python2.7/dist-packages/cloudinit/helpers.py", line 197, in run
    results = functor(*args)
  File "/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_user.py", line 38, in handle
    util.runparts(runparts_path)
  File "/usr/lib/python2.7/dist-packages/cloudinit/util.py", line 652, in runparts
    % (len(failed), len(attempted)))
RuntimeError: Runparts: 1 failures in 1 attempted commands

**Comment by sivaprasad-kiranum** [comment]
Finally figured out the issue. I had sent parameter for Banner display as a string and not as a path in s3 and cloud init was failing because of it.

**Comment by EArbeitman** [comment]
hi. Im running into the same issue. I created my own bucket with the contents of the repo, but Il still getting the same error. Any ideas?

**Comment by Higherings** [comment]
I hit the same issue, but I can't figured out the problem, I ran the template without modifications in Account A and failed, the same template and parameters in Account B and succeed, both accounts in the same Region: us-east2.

**Comment by mseld** [comment]
My Issue solved When I disabled the banner message

**Comment by quickzebra** [comment]
got the same issue.  don't know what to do.    didn't change the default values based on the instruction below :Unless you are customizing the Quick Start templates for your own deployment projects, we recommend that you keep the default settings for the parameters labeled Quick Start S3 bucket name, Quick Start S3 bucket Region, and Quick Start S3 key prefix. Changing these parameter settings automatically updates code references to point to a new Quick Start location. For more information, see the AWS Quick Start Contributor’s Guide.

**Comment by malick-it** [comment]
> My Issue solved When I disabled the banner message

This solved my issue too. Thanks !
